# Generated by Django 5.1.1 on 2024-09-22 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltvibe', '0002_user_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
