# Generated by Django 5.1.1 on 2024-09-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltvibe', '0003_rename_orders_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(default='your_default_value', max_length=100),
        ),
    ]
